name: Stress test runner

run-name: ${{ inputs.num_runner }} stress test runner to run on ${{ inputs.runner }} using ${{ inputs.num_worker }} workers for ${{ inputs.timeout }} that use ${{ inputs.mem_usage }} of MB each worker

on:
  workflow_dispatch:
    inputs:
      runner:
        default: self-hosted
        description: Runner
        type: string
        required: true
      num_worker:
        default: 2
        description: spawn N workers spinning on malloc()/free()
        type: number
        required: true
      num_runner:
        default: 2
        description: spawn N of github-runner at the same time
        type: number
        required: true
      mem_usage:
        default: 128M
        description: malloc B bytes per vm worker
        type: string
        required: true
      timeout:
        default: 60s
        description: timeout after N seconds
        type: string
        required: true
      verbose:
        default: false
        description: to print verbose info of stress test runner
        type: boolean
        required: false
  push:
    branches:
      - chore/load-test

jobs:
  gen_matrix:
    runs-on: ${{ inputs.runner }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo -n "matrix=" >> $GITHUB_OUTPUT; echo -n "[" >> $GITHUB_OUTPUT; for ((i=1; i<=${{ inputs.num_runner }}; i++)); do echo -n "$i" >> $GITHUB_OUTPUT; [ $i -ne ${{ inputs.num_runner }} ] && echo -n "," >> $GITHUB_OUTPUT; done; echo "]" >> $GITHUB_OUTPUT

  deploy:
    needs: gen_matrix
    strategy:
      matrix:
        version: ${{ fromJSON(needs.gen_matrix.outputs.matrix) }}
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Install stress test app
        run: sudo apt-get update && sudo apt-get install -y stress

      - name: Run stress test app verbosely
        if: ${{ inputs.verbose }}
        run: /usr/bin/stress --vm ${{ inputs.num_worker }} --vm-bytes ${{ inputs.mem_usage }} --timeout ${{ inputs.timeout }}
      - name: Run stress test app
        if: ${{ inputs.verbose}} != true
        run: /usr/bin/stress --vm ${{ inputs.num_worker }} --vm-bytes ${{ inputs.mem_usage }} --timeout ${{ inputs.timeout }}
    
